# Generated by Django 6.0.1 on 2026-01-19 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='core.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('sports', 'スポーツ'), ('music', '音楽'), ('culture', '文化/趣味'), ('volunteer', 'ボランティア'), ('it', 'IT/開発'), ('study', '勉強/ゼミ'), ('other', 'その他')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='circle',
            name='name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
