# Generated by Django 6.0.1 on 2026-02-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='frequency',
            field=models.CharField(blank=True, choices=[('weekly1', '週1回'), ('weekly2', '週2回'), ('weekly3', '週3回'), ('monthly', '月数回'), ('irregular', '不定期')], default='weekly2', max_length=20),
        ),
        migrations.AddField(
            model_name='circle',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='circle',
            name='place',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='circle',
            name='x_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
