# Generated by Django 6.0.1 on 2026-02-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_circle_frequency_circle_instagram_url_circle_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='activity_days',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='members_count',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='sns_link',
        ),
        migrations.AddField(
            model_name='circle',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='circle_avatars/'),
        ),
        migrations.AddField(
            model_name='circle',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='circle',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
