# Generated by Django 6.0.1 on 2026-02-25 00:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.circle_cover_path),
        ),
        migrations.AddField(
            model_name='circle',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='circle',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.circle_icon_path),
        ),
    ]
